# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Folinas Socials Tool\ui\PickUploadAccountWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(729, 453)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/icon-sw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayoutForTable = QtWidgets.QVBoxLayout()
        self.verticalLayoutForTable.setObjectName("verticalLayoutForTable")
        self.verticalLayout.addLayout(self.verticalLayoutForTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.doIt = QtWidgets.QPushButton(self.frame)
        self.doIt.setObjectName("doIt")
        self.horizontalLayout.addWidget(self.doIt)
        self.tickAllBtn = QtWidgets.QPushButton(self.frame)
        self.tickAllBtn.setObjectName("tickAllBtn")
        self.horizontalLayout.addWidget(self.tickAllBtn)
        self.untickAllBtn = QtWidgets.QPushButton(self.frame)
        self.untickAllBtn.setObjectName("untickAllBtn")
        self.horizontalLayout.addWidget(self.untickAllBtn)
        self.clearAllUploader = QtWidgets.QPushButton(self.frame)
        self.clearAllUploader.setObjectName("clearAllUploader")
        self.horizontalLayout.addWidget(self.clearAllUploader)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setStyleSheet("margin-top:10px")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.whichIndex = QtWidgets.QLabel(self.centralwidget)
        self.whichIndex.setMaximumSize(QtCore.QSize(900, 16777215))
        self.whichIndex.setStyleSheet("border-left:1px solid gray;\n"
"border-right:1px solid gray;")
        self.whichIndex.setText("")
        self.whichIndex.setWordWrap(True)
        self.whichIndex.setObjectName("whichIndex")
        self.gridLayout.addWidget(self.whichIndex, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bảng chọn tài khoản để upload"))
        self.doIt.setText(_translate("MainWindow", "Thực hiện"))
        self.tickAllBtn.setText(_translate("MainWindow", "Chọn tất cả"))
        self.untickAllBtn.setText(_translate("MainWindow", "Bỏ chọn tất cả"))
        self.clearAllUploader.setText(_translate("MainWindow", "Xoá toàn bộ trong bảng chính"))
        self.label_10.setText(_translate("MainWindow", "Bạn đang chuẩn bị áp dụng cho các video có thứ tự trong bảng dưới đây:"))
import resource_rc
