# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Folinas Socials Tool\ui\reportWorkerStickWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 770)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/icon-sw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
"background:white;\n"
"border: 1px solid #a4b0be;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainWidgetFrame = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainWidgetFrame.sizePolicy().hasHeightForWidth())
        self.mainWidgetFrame.setSizePolicy(sizePolicy)
        self.mainWidgetFrame.setMinimumSize(QtCore.QSize(400, 0))
        self.mainWidgetFrame.setMaximumSize(QtCore.QSize(711, 16777215))
        self.mainWidgetFrame.setStyleSheet("")
        self.mainWidgetFrame.setObjectName("mainWidgetFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainWidgetFrame)
        self.verticalLayout.setContentsMargins(0, 0, 4, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLeftWidget = QtWidgets.QWidget(self.mainWidgetFrame)
        self.titleLeftWidget.setStyleSheet("\n"
"QPushButton{\n"
"    \n"
"    border: 1px solid #a4b0be;\n"
"    border-radius: 3px;\n"
"    color: #2f3542;\n"
"    background: white;\n"
"    padding: 3px 9px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    border: 0px solid #85C88A;\n"
"    color: white;\n"
"    background-color: #85C88A;\n"
"}\n"
"")
        self.titleLeftWidget.setObjectName("titleLeftWidget")
        self.horizontalLayoutTitleLeftWidget = QtWidgets.QHBoxLayout(self.titleLeftWidget)
        self.horizontalLayoutTitleLeftWidget.setContentsMargins(0, 0, 0, 9)
        self.horizontalLayoutTitleLeftWidget.setSpacing(3)
        self.horizontalLayoutTitleLeftWidget.setObjectName("horizontalLayoutTitleLeftWidget")
        self.mainTitle = QtWidgets.QLabel(self.titleLeftWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mainTitle.setFont(font)
        self.mainTitle.setStyleSheet("color:#2f3542;\n"
"border: 0;\n"
"border-top:0;\n"
"border-left:0;\n"
"border-right:0;\n"
"border-bottom:2px solid #2f3542;\n"
"padding-bottom:3px")
        self.mainTitle.setObjectName("mainTitle")
        self.horizontalLayoutTitleLeftWidget.addWidget(self.mainTitle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutTitleLeftWidget.addItem(spacerItem)
        self.verticalLayout.addWidget(self.titleLeftWidget)
        self.scrollArea = QtWidgets.QScrollArea(self.mainWidgetFrame)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setStyleSheet("QScrollArea#scrollArea{\n"
"    border:0\n"
"}")
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 396, 667))
        self.scrollAreaWidgetContents.setStyleSheet("QWidget#scrollAreaWidgetContents{\n"
"    background:white\n"
"}")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayoutForWorker = QtWidgets.QVBoxLayout()
        self.verticalLayoutForWorker.setContentsMargins(0, 0, 0, -1)
        self.verticalLayoutForWorker.setSpacing(5)
        self.verticalLayoutForWorker.setObjectName("verticalLayoutForWorker")
        self.verticalLayout_4.addLayout(self.verticalLayoutForWorker)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.mainWidgetFrame)
        self.lineToDrag1 = QtWidgets.QFrame(self.frame)
        self.lineToDrag1.setFrameShape(QtWidgets.QFrame.VLine)
        self.lineToDrag1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineToDrag1.setObjectName("lineToDrag1")
        self.horizontalLayout.addWidget(self.lineToDrag1)
        self.screenLayoutWidget = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.screenLayoutWidget.sizePolicy().hasHeightForWidth())
        self.screenLayoutWidget.setSizePolicy(sizePolicy)
        self.screenLayoutWidget.setStyleSheet("")
        self.screenLayoutWidget.setObjectName("screenLayoutWidget")
        self.rightLayout_3 = QtWidgets.QVBoxLayout(self.screenLayoutWidget)
        self.rightLayout_3.setContentsMargins(0, 0, 0, 0)
        self.rightLayout_3.setSpacing(0)
        self.rightLayout_3.setObjectName("rightLayout_3")
        self.verticalWidget_2 = QtWidgets.QWidget(self.screenLayoutWidget)
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.titleRightWidgetScreen = QtWidgets.QWidget(self.verticalWidget_2)
        self.titleRightWidgetScreen.setStyleSheet("QWidget#titleRightWidget{\n"
"    border: 1px solid #a4b0be;\n"
"    border-top:0;\n"
"    border-left:0;\n"
"    border-right:0;\n"
"}\n"
"QPushButton{\n"
"    \n"
"\n"
"    padding: 3px 9px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    border: 0px solid #85C88A;\n"
"    color: white;\n"
"    background-color: #85C88A;\n"
"}\n"
"")
        self.titleRightWidgetScreen.setObjectName("titleRightWidgetScreen")
        self.horizontalLayouTtitleRightWidget_4 = QtWidgets.QHBoxLayout(self.titleRightWidgetScreen)
        self.horizontalLayouTtitleRightWidget_4.setContentsMargins(0, 0, 0, 11)
        self.horizontalLayouTtitleRightWidget_4.setSpacing(3)
        self.horizontalLayouTtitleRightWidget_4.setObjectName("horizontalLayouTtitleRightWidget_4")
        self.thirdTitle_3 = QtWidgets.QLabel(self.titleRightWidgetScreen)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.thirdTitle_3.setFont(font)
        self.thirdTitle_3.setStyleSheet("color:#2f3542;\n"
"border: 0;\n"
"border-top:0;\n"
"border-left:0;\n"
"border-right:0;\n"
"border-bottom:2px solid #2f3542;\n"
"padding-bottom:3px")
        self.thirdTitle_3.setObjectName("thirdTitle_3")
        self.horizontalLayouTtitleRightWidget_4.addWidget(self.thirdTitle_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayouTtitleRightWidget_4.addItem(spacerItem2)
        self.line = QtWidgets.QFrame(self.titleRightWidgetScreen)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayouTtitleRightWidget_4.addWidget(self.line)
        self.label_30 = QtWidgets.QLabel(self.titleRightWidgetScreen)
        self.label_30.setObjectName("label_30")
        self.horizontalLayouTtitleRightWidget_4.addWidget(self.label_30)
        self.verticalLayout_8.addWidget(self.titleRightWidgetScreen)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.verticalWidget_2)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(652, 0))
        self.scrollArea_2.setStyleSheet("\n"
"QScrollArea#scrollArea_2{\n"
"    border:0px solid rgba(0,0,0,.3);\n"
"}")
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.gridWidgetForScreen = QtWidgets.QWidget()
        self.gridWidgetForScreen.setGeometry(QtCore.QRect(0, 0, 827, 665))
        self.gridWidgetForScreen.setStyleSheet("QWidget#gridWidgetForScreen{\n"
"    border:0;\n"
"    background:white;\n"
"}")
        self.gridWidgetForScreen.setObjectName("gridWidgetForScreen")
        self.gridLayoutForScreen = QtWidgets.QGridLayout(self.gridWidgetForScreen)
        self.gridLayoutForScreen.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutForScreen.setSpacing(0)
        self.gridLayoutForScreen.setObjectName("gridLayoutForScreen")
        self.scrollArea_2.setWidget(self.gridWidgetForScreen)
        self.verticalLayout_8.addWidget(self.scrollArea_2)
        self.rightLayout_3.addWidget(self.verticalWidget_2)
        self.horizontalLayout.addWidget(self.screenLayoutWidget)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hàng chờ nhà máy trình duyệt"))
        self.mainTitle.setText(_translate("MainWindow", "Hàng chờ:"))
        self.thirdTitle_3.setText(_translate("MainWindow", "Màn hình theo dõi"))
        self.label_30.setText(_translate("MainWindow", "đang cố định 2 cột"))
import resource_rc
