# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Folinas Socials Tool\ui\uploadSettingsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(441, 134)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.reels = QtWidgets.QRadioButton(self.horizontalWidget)
        self.reels.setObjectName("reels")
        self.horizontalLayout.addWidget(self.reels)
        self.videos = QtWidgets.QRadioButton(self.horizontalWidget)
        self.videos.setObjectName("videos")
        self.horizontalLayout.addWidget(self.videos)
        self.verticalLayout.addWidget(self.horizontalWidget)
        self.horizontalWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.shorts = QtWidgets.QRadioButton(self.horizontalWidget_2)
        self.shorts.setObjectName("shorts")
        self.horizontalLayout_2.addWidget(self.shorts)
        self.normal = QtWidgets.QRadioButton(self.horizontalWidget_2)
        self.normal.setObjectName("normal")
        self.horizontalLayout_2.addWidget(self.normal)
        self.verticalLayout.addWidget(self.horizontalWidget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cài đặt upload"))
        self.label.setText(_translate("MainWindow", "Kiểu upload Facebook:"))
        self.reels.setText(_translate("MainWindow", "reels"))
        self.videos.setText(_translate("MainWindow", "videos"))
        self.label_2.setText(_translate("MainWindow", "Kiểu upload Youtube:"))
        self.shorts.setText(_translate("MainWindow", "shorts"))
        self.normal.setText(_translate("MainWindow", "normal"))
